#!/bin/bash
[ `id -u` -ne 0 ] && {
	sudo $0 $@
	exit $?
}
SOURCE_FOLDER='/home/kiosk'
DEST_FILE='/home/profile.tbz'

service gdm stop
pushd $SOURCE_FOLDER
	sudo tar cjpf $DEST_FILE --exclude="*.qcow2" -- .[^.]* *
popd
