#!/bin/bash
source /usr/local/lib/kiosk/administration

BASE_QCOW='/var/lib/libvirt/images/win10.qcow2'
DEST_QCOW="${KIOSK_PROFILE}/image.qcow2"
RUN_QCOW="${KIOSK_PROFILE}/domain.qcow2"

virsh shutdown --domain win10 &> /dev/null
virsh destroy win10-ro &> /dev/null
rm "${KIOSK_PROFILE}/image.qcow2" &> /dev/null

qemu-img create \
	-f qcow2 -F qcow2 \
	-b $BASE_QCOW \
	$DEST_QCOW
chown libvirt-qemu:kvm $DEST_QCOW
rm -f $RUN_QCOW &> /dev/null
cp -p $DEST_QCOW $RUN_QCOW
