#!/bin/bash
source /usr/local/lib/kiosk/administration
SOURCE_QCOW="${KIOSK_PROFILE}/image.qcow2"
RUN_QCOW="${KIOSK_PROFILE}/domain.qcow2"
virsh destroy --domain win10-ro &> /dev/null
TEMP=$(mktemp -d);
mv -f $RUN_QCOW $TEMP/&> /dev/null
cp -p $SOURCE_QCOW $RUN_QCOW
chown kiosk:kiosk $RUN_QCOW
( do-patch-image || {
	echo "Patch failed: restoring old image"
	mv -f $TEMP/$(basename $RUN_QCOW) $RUN_QCOW&> /dev/null
} ) | tee -a /root/patch.log
virsh create "${KIOSK_PROFILE}/domain.xml"
