#!/bin/bash
source /usr/local/lib/kiosk/administration

SOURCE_PATH='\/var\/lib\/libvirt\/images\/win10.qcow2'
DEST_PATH=$(echo ${KIOSK_PROFILE}/domain.qcow2 | sed -r "s/([/])/\\\\\1/g")
SOURCE_UUID=$KIOSK_SOURCE_UUID
DEST_UUID=$KIOSK_RT_UUID
DOMAIN_FILE="${KIOSK_PROFILE}/domain.xml"
virsh dumpxml win10 \
	| sed -r "s/${SOURCE_PATH}/${DEST_PATH}/g" \
	| sed -r "s/${SOURCE_UUID}/${DEST_UUID}/g" \
	| sed -r "s/win10/win10-ro/" > $DOMAIN_FILE
virsh destroy win10-ro &> /dev/null
virsh undefine win10-ro &> /dev/null
