#!/bin/bash
[ `id -u` -ne 0 ] && {
        sudo $0 $@
        exit $?
}
SOURCE_PATH='\/var\/lib\/libvirt\/images\/win10.qcow2'
DEST_PATH='\/home\/kiosk\/domain.qcow2'
SOURCE_UUID='2dd1008c-2f84-4f28-bbbe-72f80d64a664'
DEST_UUID='4283d346-1fc2-11ec-abad-8f869913231d'
DOMAIN_FILE="/home/kiosk/domain.xml"
virsh dumpxml win10 \
	| sed -r "s/${SOURCE_PATH}/${DEST_PATH}/g" \
	| sed -r "s/${SOURCE_UUID}/${DEST_UUID}/g" \
	| sed -r "s/win10/win10-ro/" > $DOMAIN_FILE
virsh destroy win10-ro &> /dev/null
virsh undefine win10-ro &> /dev/null
