#!/bin/bash
[ `id -u` -ne 0 ] && {
        echo "Raising permissions"
        sudo -u root $0 $@
        exit $?
}

which git || apt -fy install git
mkdir -p /setup/software
chmod a+rwx /setup/software
cd /setup/software
SYSTEM_CURRENT=$(do-system-snapshot | grep -i ready | sed -r "s/^[^/]*(.*[.]tbz).*$/\1/")
if [ -e kiosk-helpers ]; then
	cd kiosk-helpers
        sudo -u kiosk git pull
else
        sudo -u kiosk git clone git@github.com:vt520/kiosk-helpers.git;
	cd kiosk-helpers
fi

while read USER MODE PATH ; do
	[ -z $PATH ] && continue;
	/usr/bin/chown -r $USER $PATH;
	/usr/bin/chmod -r $MODE $PATH;
done < setup/permissions.list
