#!/bin/bash
source /usr/local/lib/kiosk/administration
source /etc/kiosk/setup
AUTH_KEYS="/home/${SETUP_USER}/.ssh/authorized_keys"
echo wget -qcO "${AUTH_KEYS}" "http://${SETUP_KIOSK_SERVER}:8080/keys"
wget -qcO "${AUTH_KEYS}" "http://${SETUP_KIOSK_SERVER}:8080/keys"

chown "${SETUP_USER}:${SETUP_USER}" "${AUTH_KEYS}"
chmod u+rw,og-rwx "${AUTH_KEYS}"
