#!/bin/bash

TEMP_TARBALL=$(tempfile)
SYSTEM_TARBALL_FOLDER="/etc/kiosk"

SYSTEM_TARBALL="${SYSTEM_TARBALL_FOLDER}/last-system-image.tbz"

[ -e "$SYSTEM_TARBALL" ] && {
	SYSTEM_BACKUP="${SYSTEM_TARBALL_FOLDER}/system-image-$(date '+%Y-%m-%d').tbz"
	echo Saving old system to $SYSTEM_BACKUP
	mv "$SYSTEM_TARBALL" "${SYSTEM_BACKUP}"
}

echo "Removing empty folders"
rm -rf $(find -empty)

cd . #refresh directory

tar cvjpf "$TEMP_TARBALL" --remove-files -- \
	$(find  -maxdepth 1 -type d -not -path  "./setup" -and -not -iname ".*") LICENSE

mv "$TEMP_TARBALL" "$SYSTEM_TARBALL"

cat <<- EOF

Preparing to apply image;
press enter to finish installing;
CTRL+C for a rather ungraceful exit
EOF
read

cd /
tar xvjpf $SYSTEM_TARBALL
