#!/bin/bash

TEMP_TARBALL=$(tempfile)
SYSTEM_TARBALL_FOLDER="/etc/kiosk"

SYSTEM_TARBALL="${SYSTEM_TARBALL_FOLDER}/last-system-setup.tbz"

[ -e "$SYSTEM_TARBALL" ] && {
	SYSTEM_BACKUP="${SYSTEM_TARBALL_FOLDER}/system-setup-$(date '+%Y-%m-%d').tbz"
	echo Saving old system to $SYSTEM_BACKUP
	mv "$SYSTEM_TARBALL" "${SYSTEM_BACKUP}"
}

echo "Removing empty folders"
rm -rf $(find -empty)

cd . #refresh directory

tar cjpf "$TEMP_TARBALL" --remove-files -- \
	$(find  -maxdepth 1 -type d -not -path  "./setup" -and -not -iname ".*") LICENSE
mkdir -p "$(dirname $SYSTEM_TARBALL)" > /dev/null
mv "$TEMP_TARBALL" "$SYSTEM_TARBALL"

cat <<- EOF

Preparing to apply image in 10 seconds
CTRL+C for a rather ungraceful exit
EOF
sleep 10

cd /
tar xjpf $SYSTEM_TARBALL
