#!/bin/bash
[ -e etc/kiosk/setup ] && source etc/kiosk/setup

[ -n "$SETUP_HASHWORD" ] && {
	[ -e "/etc/kiosk/setup" ] || {
		echo "No setup found"
		exit 1
	}
	pushd / > /dev/null
	echo "Downloading initial system image"

	wget --show-progress \
		-qcO /dev/stdout "$SETUP_DOMAIN_IMAGE_URL" \
		| openssl enc \
			-d -pbkdf2 \
			-iter 100000 \
			-pass env:SETUP_HASHWORD \
		| tar xj
	popd > /dev/null
}
