#!/bin/bash

[ -n "$SETUP_HASHWORD" ] && {
	echo "Downloading initial system image"

	# declare -x SETUP_DOMAIN_IMAGE_URL="http://kiosks.energyservices.org:8080/image"

	wget --show-progress \
		-qcO /dev/stdout "$SETUP_DOMAIN_IMAGE_URL" \
		| openssl enc \
			-d -pbkdf2 \
			-iter 100000 \
			-pass env:SETUP_HASHWORD \
		| tar xjv
}
