#!/bin/bash
declare -x GIT_SSH_COMMAND='ssh -i /etc/kiosk/protected/identity -o IdentitiesOnly=yes'
. /etc/profile
. setup/promote
if [ "${SETUP_MODE:-INSTALL}" != "INSTALL" ]; then
	[ -e /etc/kiosk/setup ] || {
		echo "Cannot update without an existing install"
		exit 1
	}
	source /etc/kiosk/setup
	PERM_USER_ID=$(id -u $SETUP_USER)
fi

PERM_USER="$(id -nu $PERM_USER_ID)"
PERM_GROUP="$(id -ng $PERM_USER_ID)"
EXEC_FOLDER="$(pwd)"

cat <<- EOF
	Welcome to the SD/IO Installer
	Please wait while we freshen things up a bit
EOF

until [ -e $(pwd)/.git ]; do
	cd ..
	[ "$(pwd)" == "/" ] && {
		cat <<- EOF
			Could not find the GIT repository while searching up the directory tree
			please try again from the setup or kiosk-helpers directory.
		EOF
		cd "$EXEC_FOLDER"
		exit 1
	}
done

SETUP_LOCATION="$(pwd)/setup"

echo "Checking SSH permissions"
chmod a-x,u+rw,go-rw /home/$PERM_USER/.ssh/*
echo "Checking git permissions"

chown -R "$PERM_USER:$PERM_GROUP" -- .
chmod -R a+rw .

echo "Updating Source"
git reset --hard
git pull

echo "Configuting Setup Modules"
chmod a+xr $(find setup -maxdepth 1 -type f -and -not -iname "*.*")
chmod a+xr $(find setup/templates -type f)

echo
echo "Configuring SD/OS Build"
if [ "${SETUP_MODE:-INSTALL}" == "INSTALL" ]; then
	setup/prompts
else
	echo "Upgrading using existing setup"
	cp /etc/kiosk/setup etc/kiosk/setup
fi

echo "Continuing Setup with fresh source"
source setup/postgit
