#!/bin/bash
echo $0 ${BASH_SOURCE[1]}
exit
declare -x GIT_SSH_COMMAND='ssh -i /etc/kiosk/protected/identity -o IdentitiesOnly=yes'
. /etc/profile
. setup/promote
if [ "${SETUP_MODE:-INSTALL}" != "INSTALL" ]; then
	[ -e /etc/kiosk/setup ] || {
		echo "Cannot update without an existing install"
		exit 1
	}
	source /etc/kiosk/setup
	PERM_USER_ID=$(id -u $SETUP_USER)
fi

PERM_USER="$(id -nu $PERM_USER_ID)"
PERM_GROUP="$(id -ng $PERM_USER_ID)"
EXEC_FOLDER="$(pwd)"

cat <<- EOF
	Welcome to the SD/IO Installer
	Please wait while we freshen things up a bit
EOF

#until [ -e $(pwd)/.git ]; do
#	cd ..
#	[ "$(pwd)" == "/" ] && {
#		cat <<- EOF
#			Could not find the GIT repository while searching up the directory tree
#			please try again from the setup or kiosk-helpers directory.
#		EOF
#		cd "$EXEC_FOLDER"
#		exit 1
#	}
#done

[ -e ".git" ] || {
	echo "Upgrading to GIT repository..."
	git clone --bare git@github.com:vt520/kiosk-helpers.git .git &> /dev/null
	git init &> /dev/null
}


SETUP_LOCATION="$(pwd)/setup"

echo "Updating Source to Current"
git reset --hard &> /dev/null
git pull &> /dev/null

echo
echo "Checking setup executable flags"
chmod a+xr $(find setup -maxdepth 1 -type f -and -not -iname "*.*")
chmod a+xr $(find setup/templates -type f)

echo
echo "Configuring SD/OS Build"
cd .
if [ "${SETUP_MODE:-INSTALL}" == "INSTALL" ]; then
	setup/prompts
else
	echo "Upgrading using existing setup"
	cp /etc/kiosk/setup etc/kiosk/setup
fi

echo "Continuing Setup with fresh source"
source setup/postgit

