#!/bin/bash
echo "Upgrading base packages"
( apt-get update -qq && apt-get -qqy upgrade ) > /dev/null || {
	echo "Base upgrades failed"
	exit 1
}

echo "Checking individual packages"
while read PACKAGE ; do
	[ -z "$PACKAGE" ] && continue;
	echo -n "$PACKAGE "
	(
		( echo -n " downloading... ";	apt-get install -qdy $PACKAGE ) \
		|| ( echo -n "installing... "; apt-get install -qy $PACKAGE )
	) || {
		echo $PACKAGE failed to install
		exit 1
	}
	echo ok
done < setup/packages.list
