#!/bin/bash
echo "Upgrading base packages"
( apt-get update -qq && apt-get -qqy upgrade ) > /dev/null || {
	echo "Base upgrades failed"
	exit 1
}

echo "Checking individual packages ( $( wc -l < setup/packages.list ) packages total )"
while read PACKAGE ; do
	[ -z "$PACKAGE" ] && continue;
	echo "Checking $PACKAGE"
	(
		( apt-get install -qqdy $PACKAGE ) \
		&& ( DEBIAN_FRONTEND=noninteractive \
 			apt-get install -qqy $PACKAGE )
	) || {
		echo $PACKAGE failed to install
		exit 1
	}
	echo ok
done < setup/packages.list
