#!/bin/bash

for FILE in $(find -type f); do
	FILE="${FILE#./}"
	[ -e "/$FILE" ] && {
		echo Found $FILE
		mkdir -p patches/$(dirname $FILE) 2> /dev/null
		diff "/$FILE" "$FILE" > "patches/${FILE}.patch" || {
			rm "patches/${FILE}.patch"
		}
		rm "$FILE"
	}
done
