#!/bin/bash

while read USER MODE PATH ; do
	[ -z "$PATH" ] && continue;
	[ "$USER" == ":runtime:" ] && USER="$(/usr/bin/id -nu 1000):$(/usr/bin/id -ng 1000)"
	echo Changing permissions $PATH $USER $MODE
	/usr/bin/chown -R $USER $PATH;
	/usr/bin/chmod -R $MODE $PATH;
done < setup/permissions.list
