#!/bin/bash
function bail() {
	echo "$@"
	exit 1
}

source /etc/kiosk/setup
source /usr/local/lib/kiosk/administration

SETUP_HOSTNAME=${SETUP_USER:=kooky}-$(printf "%02i" ${SETUP_KIOSK_ID:=1})

do-update-keys

rm /etc/X11/sawfish/site-init.d/00debian.jl &> /dev/null
rm /etc/X11/sawfish/site-init.d/00menu.jl &> /dev/null

echo
echo "Configuring EFI and Bootloader"

update-initramfs -u &> /dev/null
update-grub &> /dev/null

echo
echo "Setting up system services"
systemctl daemon-reload &> /dev/null || bail "Could not reload daemons"
systemctl enable system-updates.timer &> /dev/null || bail "Update service not configured"
systemctl enable management.service &> /dev/null || bail "Management service not configured"
systemctl enable display-manager.service &> /dev/null || bail "Display manager not configured"
systemctl disable cloud-init &> /dev/null || bail "Could not disable cloud init"

XDG=/run/user/$(id -u $SETUP_USER)

sudo -u $SETUP_USER XDG_RUNTIME_DIR=$XDG \
	systemctl --user daemon-reload &> /dev/null || bail "Could not reload user daemons"
sudo -u $SETUP_USER XDG_RUNTIME_DIR=$XDG \
	systemctl --user enable remote &> /dev/null || bail "Could not enable remote unit"

systemctl disable apparmor.service &> /dev/null

echo
echo "Configuring System Login"
restorecon /etc/hosts
restorecon /etc/hostname
USER_ID=$(id -u $SETUP_USER)
USER_PATH=$(dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserById int64:$USER_ID)

dbus-send --print-reply --system --dest=org.freedesktop.Accounts $USER_PATH org.freedesktop.Accounts.User.SetXSession string:'kiosk'

echo 
echo "Applying profile"
do-reset-profile
make-key > "${KIOSK_PROFILE}/.nonce"

echo "Done"

rm /var/www/session &>/dev/null
ln -s "${KIOSK_PROFILE}/.nonce" /var/www/session

exit 0
