#!/bin/bash
echo $EXEC_USER_ID
echo "Configuring permissions"

cd "$SETUP_LOCATION"
cd ..

chmod +x setup/permissions
setup/permissions

echo
echo "Configuring SD/OS Build"
setup/prompts

echo
echo "Applying Settings Templates"
setup/template

echo
echo "Checking installed packages"
setup/packages

echo
echo "Creating uninstall patches"
setup/patches

echo
echo "Creating System Tarball"

TEMP_TARBALL=$(tempfile)
SYSTEM_TARBALL=/etc/kiosk.last-system-image.tbz

[ -e "$SYSTEM_TARBALL" ] && mv "$SYSTEM_TARBALL" "${SYSTEM_TARBALL}.old"
tar cjpPf "$TEMP_TARBALL" -- *
mv "$TEMP_TARBALL" "$SYSTEM_TARBALL"

cat <<- EOF

Preparing to apply image;
press enter to finish installing;
anything else for a rather ungraceful exit
EOF

read

cd /
tar xvjpPf $SYSTEM_TARBALL
read
echo
echo "Installing / Updating Base Image"
setup/image

echo
echo "Running post-install"
setup/postinstall
