#!/bin/bash
echo $EXEC_USER_ID

cd "$SETUP_LOCATION"
cd ..
echo
echo "Configuting Setup"
chmod a+xr $(find setup -maxdepth 1 -type f -and -not -iname "*.*")
chmod a+xr $(find setup/templates -type f)

echo
echo "Configuring SD/OS Build"
setup/prompts

echo
echo "Applying Settings Templates"
setup/template

echo "Configuring permissions"
chmod +x setup/permissions
setup/permissions

echo
echo "Checking installed packages"
setup/packages

echo
echo "Creating uninstall patches"
setup/patches

echo
echo "Creating System Tarball"
setup/archive

echo
echo "Installing / Updating Base Image"
setup/image

echo
echo "Running post-install"
setup/postinstall
