#!/bin/bash

# NOTE THIS IS ONLY RELIABLE FOR ENCRYPTED FILES

FILE_HEADERS=$(tempfile)
FILE_STUB=$(tempfile)
HASH_FILE=$(tempfile)

curl -m 30 --limit-rate 1k -LD $FILE_HEADERS -o $FILE_STUB "$@" &> /dev/null
head -c 1024 $FILE_STUB > $HASH_FILE
egrep -i 'content-length|location|filename' $FILE_HEADERS | grep -v '[.]boxcloud[.]' >> $HASH_FILE
sha256sum < $HASH_FILE | sed -r "s/ - *//"
rm $FILE_HEADERS $FILE_STUB $HASH_FILE
