#!/bin/bash
source etc/kiosk/setup
for TEMPLATE in $(find setup/templates -type f); do
	echo "Applying template: $TEMPLATE"
	chmod a+x "${TEMPLATE}"
	DESTINATION=${TEMPLATE##setup/templates/}
	mkdir -p $(dirname $DESTINATION)
	. "${TEMPLATE}" > ${DESTINATION}
done
exit 0
